* Boreas

Boreas is a Sys-Admin tool focused on access control, geared towards universities.  Boreas uses a simple configuration file and will manage account creation and access for those accounts.  Boreas is proudly written in Haskell. 

** Use Case
The use case of Borease is to be organized with access control.  Lets say you are managing resources access for multiple courses at a university.  Each class may need different accesss requirements.  Lets say one class only need their students to have access for a shorter period of time than another.  Using Boreas, you can have a configuration file per class. 


#+begin_src bash
comp1234.cfg	eng3532.cfg	bio3257.cfg	bus9483.cfg
#+end_src

This allows you to manage access to your resources on a per class basis.  Note: This may need more attention is there are overlapping students.  Another example is, let say you have one class split into multiple groups.  With this multi-file strategy, you can manage each group's access. 

** How to install
*** How to build
Borease has 2 dependancies that you will have to install. You will also need to install ghc and cabal via GHCup (or by other means).

#+begin_src bash
sudo apt install libcurl4-openssl-dev libgmp-dev
cabal install
#+end_src

*** How to build via Nix
Boreas uses Nix flakes (via the haskell-flake module). Everything should work the same. Only thing I have ran into is if you run a 'nix flake show' you might get an error. The following command will work

#+begin_src bash
nix flake show --allow-import-from-derivation
#+end_src

From what I can tell this seems common with Haskell and Nix derivations.
To just build, you can run ** Configuration Syntax The configuration file uses a simple syntax. 

#+begin_src bash
nix build
#+end_src

** Configuration Syntax
The configuration file uses a simple syntax.
#+begin_src cfg
universityID : GitHubUserName
#+end_src

A colon ":" is used as the delimiter between the universityID and the Github Username.  The universityID is used as the account name to be created (i.e., what a  student would login as). The GitHub username is used as the source to scrape keys from for a particular user. The relation between the universityID and GitHub username is an important one and is the basis of this tool. 

** How-to
Currently there is no man page for Boreas.  The best that is provided is the [-h | --help] options.

#+begin_src bash
Usage: boreas COMMAND

  Boreas Command

Available options:
  -h,--help                Show this help text

Available commands:
  run                      Create accounts, scrape keys, give access.
  update                   Scrape keys, update access.
  purge                    Purge keys and accounts, remove access.
#+end_src
