name: "Nix-Build"
on: 
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
      - run: nix-build
      - run: nix-shell --run "echo-OK"
    
